### ISSUE TITLE
Slider Grip not movng smoothly when mouse pointer moves away from it.

### ISSUE THREAD

**Issue by jain1anuj** [Mottie/Pathslider#5]
Hi,

Slider Grip not movng smoothly when mouse pointer moves away from it. I tried to fix it but couldn't. Could you please help me out ?

**Comment by Mottie** [comment]
Hi @jain1anuj!

Because of the complex shapes that can be used, if you move too far from the path, the grip position calculation becomes more difficult to determine.

DId you try adjusting any of the ["Smoothness Tweaks" options](https://github.com/Mottie/Pathslider/wiki/Options#smoothness-tweaks)?

I know this plugin needs a lot of work. I have a lot of ideas for making it better, I just don't have a lot of time right now to work on it.

**Comment by jain1anuj** [comment]
Hi, 

I tried using the Tolerance and Data Points value to make it smooth. I am using the bezier curve as a shape for grip movement. When user select the grip and moves it, it moves perfect. But when user drags the mouse pointer away from the grip whle mousedown, grip jumps.

Can you please provide some idea how to make it move strictly on the bezier curve ?

**Comment by Mottie** [comment]
Well, if you want to help...

I think [projecting the mouse position on the Bézier curve](http://pomax.github.io/bezierinfo/#projections) is not an ideal solution (move the mouse right and left over P6, or above and below P7 in the demo on that page) because the grip will jump quite some distance.

What this plugin does is:
* It creates an array of data points (percent, curve x & y position) on initialization.
* It then tries to find the grip position based on the mouse position by comparing the curve x & y  position within the range (around the size of the grip) of the mouse position.
* The tolerance is how close the mouse x & y match the curve x & y values.
* Once it find a close match, it returns the corresponding percent.

If a curve has a tight angle (like in the [builder demo](http://mottie.github.io/Pathslider/builder.html) preset number 5) the above calculation works great, but using projections won't work so well.

I think what is needed is a combination of the two, or maybe add an option to allow switching between the two methods.

**Comment by jain1anuj** [comment]
I helped you by fixing the UI issue for grip in Safari for WIndows platform. :)

**Comment by Mottie** [comment]
Did you try setting the `range` to some big number, like 1000?

http://jsfiddle.net/ZAtGE/34/

**Comment by jain1anuj** [comment]
Hi Mottie,

Thanks for the early response and solution, It worked for me. :). Also i am waiting for the ideas that you have for this plugin.
